"""
Standup update action handler - mock/demo mode.
Generates a concise yesterday/today/blockers standup update.
"""
from datetime import datetime


def handle_standup(message: str, environment: str) -> dict:
    now = datetime.utcnow().strftime("%Y-%m-%d")
    response = f"""## Standup Update Draft

**Date:** {now}
**Environment:** {environment.upper()}

---

### Yesterday
- Investigated and documented root cause for the reported issue: *{message[:120] if len(message) > 10 else 'CloudOps issue'}*
- Reviewed relevant runbooks and escalation procedures
- Coordinated with the platform team on current environment status

### Today
- Follow up on findings from yesterday's investigation
- Complete documentation and update the incident or change record
- Validate fix or workaround in the {environment.upper()} environment
- Check monitoring dashboards for related alerts

### Blockers
- Awaiting approval from the infrastructure team (if applicable)
- No critical blockers at this time — update if status changes

---
*This standup draft was generated by OpsNexus. Update with actual work items before posting.*
*No real systems were accessed to generate this summary.*"""

    return {
        "summary": f"Standup update draft generated for {environment}",
        "response": response,
    }
